server:
  port: 9002
spring:
  application:
    name: hrm-course
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hrm-course
    username: root
    password: xrj5201314
mybatis-plus:
  mapper-locations: classpath:cn/xiaji/hrm/mapper/*Mapper.xml
  type-aliases-package: cn.xiaji.hrm.domain,cn.xiaji.hrm.query